language: julia

# avoids duplicate tests in PRs
branches:
  only:
    - master

coveralls: true

os:
  - linux
  - osx

julia:
  - 1.0
  - 1
  - nightly

matrix:
  allow_failures:
    - julia: nightly
    - os: osx
  fast_finish: true
  include:
    - os: linux
      arch: x64
    - os: linux
      arch: x86

after_success:
  - if [[ $TRAVIS_JULIA_VERSION = 1 ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
      julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
    fi

notifications:
  email: false
