name: Automatically assign PR authors

on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: TuringLang/actions/PRAssign@main
